### ISSUE TITLE
Verv som er utnevnt av styret

### ISSUE THREAD

**Issue by malinjosefsen** [anderslund/borgemusikken.no#1]
Hei Anders

det har kommet ønske om at på vervsiden skal de verv som er utnevnt av styret stå med en annen farge i boksen. Hvis det er mulig. 

Så øvrige verv deles i to: de som er utnevnt på årsmøtet av valgkomité og de verv som utnevnes av styret. 

Så om vi opprettholder blå boks med de som er utnevnt av årsmøtet, og så en gul boks (f.eks, den fargen går igjen) for de som utnevnes av styret. Jeg kan sortere de, men det blir vel litt omstrukturering på siden.

**Comment by anderslund** [comment]
Hei. 

Jeg har omsider fått laget noe nå: https://borgemusikken.no/om-oss/styret/

Du får ta en titt :-)
