### ISSUE TITLE
Opprette ny side

### ISSUE THREAD

**Issue by malinjosefsen** [anderslund/borgemusikken.no#5]
Vi skal få laget en side for BorgeAkademiet, trenger å få opprettet dette på websiden

**Comment by anderslund** [comment]
Har laget ny, tom side her:

https://borgemusikken.no/wp-admin/post.php?post=10236&action=edit

Men dette gjør du enkelt ved å peke på "Legg til" på menyen, og så "Side" i menyen som da popper opp (ikke trykk, bare pek)
